FROM public.ecr.aws/lambda/python:3.11

RUN yum update -y && \
    yum install -y gcc gcc-c++ make zlib-devel libjpeg-devel && \
    yum clean all

COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt

COPY app ${LAMBDA_TASK_ROOT}/app
COPY yolov8n.pt ${LAMBDA_TASK_ROOT}/yolov8n.pt

CMD ["app.main.handler"]
